import csv
import importlib.util
import tempfile
import unittest
from pathlib import Path

from scripts.verify_pip_vendor_record import refresh_record, verify_record


class PipVendorRecordTests(unittest.TestCase):
    def test_verify_accepts_only_installer_generated_vendor_bytecode_rows(self):
        with tempfile.TemporaryDirectory() as directory:
            site = Path(directory)
            vendor = site / "pip" / "_vendor" / "urllib3"
            info = site / "pip-26.2.1.dist-info"
            vendor.mkdir(parents=True)
            info.mkdir()
            source = vendor / "response.py"
            source.write_bytes(b"response = True\n")
            (site / "pip" / "_vendor" / "vendor.txt").write_bytes(b"urllib3==2.8.0\n")
            (site / "pip" / "_vendor" / "bom.cdx.json").write_bytes(b"{}\n")
            record = info / "RECORD"
            record.write_bytes(b"pip-26.2.1.dist-info/RECORD,,\n")
            refresh_record(site, info)

            bytecode = Path(importlib.util.cache_from_source(str(source)))
            bytecode.parent.mkdir()
            bytecode.write_bytes(b"installer-generated bytecode")
            relative = bytecode.relative_to(site).as_posix()
            with record.open("a", newline="") as stream:
                csv.writer(stream).writerow((relative, "", ""))
            verify_record(site, info)

            with record.open(newline="") as stream:
                original = list(csv.reader(stream))
            for changed_path, changed_hash, changed_size in (
                (relative, "sha256=not-blank", "1"),
                (relative.replace("response.", "missing."), "", ""),
                (relative.replace(".pyc", ".txt"), "", ""),
                (relative.replace("__pycache__/", "other-cache/"), "", ""),
            ):
                with self.subTest(path=changed_path, hash=changed_hash):
                    rows = [
                        (changed_path, changed_hash, changed_size) if row[0] == relative else row
                        for row in original
                    ]
                    with record.open("w", newline="") as stream:
                        csv.writer(stream).writerows(rows)
                    with self.assertRaises(ValueError):
                        verify_record(site, info)
            with record.open("w", newline="") as stream:
                csv.writer(stream).writerows(original)
            bytecode.unlink()
            with self.assertRaisesRegex(ValueError, "bytecode RECORD entry"):
                verify_record(site, info)
            bytecode.write_bytes(b"installer-generated bytecode")
            source.write_bytes(b"response = False\n")
            with self.assertRaisesRegex(ValueError, "digest mismatch"):
                verify_record(site, info)

    def test_refresh_covers_all_replaced_vendor_files_and_licenses(self):
        with tempfile.TemporaryDirectory() as directory:
            site = Path(directory)
            vendor = site / "pip" / "_vendor"
            info = site / "pip-26.2.1.dist-info"
            for name in ("msgpack", "pkg_resources", "urllib3"):
                package = vendor / name
                package.mkdir(parents=True)
                (package / "__init__.py").write_text(f"{name} fixed\n")
                (package / "LICENSE.txt").write_text(f"{name} license\n")
            (vendor / "vendor.txt").write_text("    urllib3==2.8.0\n")
            (vendor / "bom.cdx.json").write_text('{"components": []}\n')
            (site / "pip" / "__init__.py").write_text("unrelated\n")
            info.mkdir()
            (info / "entry_points.txt").write_text("[console_scripts]\n")
            for name in ("msgpack", "pkg_resources", "urllib3"):
                license_dir = info / "licenses" / "src" / "pip" / "_vendor" / name
                license_dir.mkdir(parents=True)
                (license_dir / "LICENSE.txt").write_text(f"{name} license\n")
            record = info / "RECORD"
            with record.open("w", newline="") as stream:
                csv.writer(stream).writerows(
                    [
                        ("pip/_vendor/urllib3/removed.py", "sha256=stale", "5"),
                        ("pip/_vendor/urllib3/__init__.py", "sha256=stale", "5"),
                        ("pip/__init__.py", "sha256=unchanged", "10"),
                        ("pip-26.2.1.dist-info/entry_points.txt", "sha256=entrypoint", "18"),
                        ("pip-26.2.1.dist-info/RECORD", "", ""),
                    ]
                )

            refresh_record(site, info)
            verify_record(site, info)
            with record.open(newline="") as stream:
                rows = {row[0]: row for row in csv.reader(stream)}
            self.assertNotIn("pip/_vendor/urllib3/removed.py", rows)
            for name in ("msgpack", "pkg_resources", "urllib3"):
                path = f"pip/_vendor/{name}/__init__.py"
                content = (site / path).read_bytes()
                self.assertEqual(rows[path][2], str(len(content)))
                self.assertTrue(rows[path][1].startswith("sha256="))
            self.assertIn("pip/_vendor/vendor.txt", rows)
            self.assertIn("pip/_vendor/bom.cdx.json", rows)
            self.assertEqual(rows["pip/__init__.py"], ["pip/__init__.py", "sha256=unchanged", "10"])
            self.assertEqual(
                rows["pip-26.2.1.dist-info/entry_points.txt"],
                ["pip-26.2.1.dist-info/entry_points.txt", "sha256=entrypoint", "18"],
            )
            self.assertIn("pip-26.2.1.dist-info/licenses/src/pip/_vendor/urllib3/LICENSE.txt", rows)
            rows.pop("pip/_vendor/urllib3/__init__.py")
            with record.open("w", newline="") as stream:
                csv.writer(stream).writerows(rows.values())
            with self.assertRaises(ValueError):
                verify_record(site, info)

    def test_verify_rejects_changed_bytes(self):
        with tempfile.TemporaryDirectory() as directory:
            site = Path(directory)
            vendor = site / "pip" / "_vendor" / "urllib3"
            info = site / "pip-26.2.1.dist-info"
            vendor.mkdir(parents=True)
            info.mkdir()
            (vendor / "__init__.py").write_text("good")
            (site / "pip" / "_vendor" / "vendor.txt").write_text("urllib3==2.8.0\n")
            (site / "pip" / "_vendor" / "bom.cdx.json").write_text("{}\n")
            (info / "RECORD").write_text("pip-26.2.1.dist-info/RECORD,,\n")
            refresh_record(site, info)
            (vendor / "__init__.py").write_text("bad")
            with self.assertRaises(ValueError):
                verify_record(site, info)


if __name__ == "__main__":
    unittest.main()
